project:
  type: website

website:
  title: "Johannes Johow (Dr. rer. nat., Dipl.-Biol.)"
  navbar:
    right:
      - about.qmd
listing:
  contents: content
  sort: "date desc"
  type: default
  categories: false
  sort-ui: false
  filter-ui: false
format:
  html:
    theme: port-hugo
    css: styles.css
    background-color: #474e3c;
